name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install ttkbootstrap
        pip install coloredlogs

    - name: Analysing the code with pylint
      run: |
        pylint --disable=R,C0116,W0603,C0116,C0103,C0301,W1405,C0303,C0114,C0115,C0112,W1401,C0209,W0123 $(git ls-files '*.py')
